/oak:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: false
      i_nn_type: none
      i_pipeline_type: depth
    left:
      i_resolution: '720'
      i_fps: 10.0
    right:
      i_resolution: '720'
      i_fps: 10.0
    stereo:
      i_publish_topic: true
      i_align_depth: true
      i_publish_synced_rect_pair: true
